# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

plugins: [jekyll-paginate,jekyll-pandoc]


paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
markdown: Pandoc
highlighter: true

pandoc:
  extensions:
#   - normalize
#   - smart
   - mathjax

# Specify if pdf latex docs need to be generated (managed by plugin generatepdf.rg in _plugins)
pdfgeneration: False


title: InvestmentMath
description: Maths for Portfolio Management 
author:
  name: InvestmentMath
  email: investmentmath@gmail.com
  bio: About InvestmentMath 
  email_md5: 726351295ec82e145928582f595aa3aa


rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

encoding: utf-8
#BASE_PATH: https://www.investmentmath.com
#BASE_PATH: http://163.172.95.171
#BASE_PATH: http://195.154.78.40:1234
BASE_PATH: http://127.0.0.1:4000
# BASE_PATH: http://dbtek.github.io/dbyll

# All links will be namespaced by BASE_PATH if defined.
# Links in your website should always be prefixed with {{ site.BASE_PATH }}
# Do not put a "/" at the end of the url.
#
# CNAME (http://yourcustomdomain.com)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK 
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Pages (http://username.github.io)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK 
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Project Pages (http://username.github.io/project-name)
#  A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
#  REQUIRED! Set BASE_PATH to "http://username.github.io/project-name"
